[project]
name = "project-02807"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "loguru>=0.7.3",
    "numpy>=2.3.4",
    "pandas>=2.3.3",
    "pretty-midi>=0.2.11",
    "seaborn>=0.13.2",
    "tqdm>=4.67.1",
]
